Use the web search api of the big register
privacybydesign/irma_big_issuer pull request #2
Opened 2018-08-14 13:15 UTC by davidv1992

Changes to make the issuer check for birthday again using the web search.

2018-08-14 17:50 UTC, aykevl approved these changes
Looks good to me, can be merged in my opinion. It's even better than what I had originally in mind.

2018-08-14 17:50 UTC, aykevl commented on src/main/java/foundation/privacybydesign/bigregister/RestApi.java
> +        //String dateOfBirthString = "";
This is unrelated to the PR and mostly a matter of taste I guess. The previous behavior was correct as long as the lines above (line 81-84) were not commented out.

2018-08-14 17:50 UTC, aykevl commented on src/main/java/foundation/privacybydesign/bigregister/RestApi.java
> +            System.out.println("BIG request error: " + e.getMessage());
Nitpick: this should be `logger.error`, but as previously discussed this is probably originally my mistake.

2018-08-15 13:57 UTC, sietseringers requested changes
Compilation currently fails because the `BIGRegisterApp` class calls `BIGService.doRequest()`  with too many parameters:
```
BIGRegisterApp.java:26: error: method doRequest in class BIGService cannot be applied to given types;
            results = service.doRequest(name, null, "");
```

2018-08-15 13:57 UTC, sietseringers commented on src/main/java/foundation/privacybydesign/bigregister/BIGWebSearch.java
> +        if (dateOfBirth != null) {
Why would the birthdate not be available? If it isn't, then we shouldn't issue anything at all. That means that by this point in the code we can assume there is a birthdate.

2018-08-15 13:57 UTC, sietseringers commented on src/main/java/foundation/privacybydesign/bigregister/BIGWebSearch.java
> +        }
I don't know if a bank will ever give anyone a gender different than these two, but if so we should probably have an `else` here that at least logs something, and maybe abort the request.

2018-08-15 13:57 UTC, sietseringers commented on src/main/java/foundation/privacybydesign/bigregister/RestApi.java
> +            bigNumber = new BIGWebSearch().getBIGNumber(familyName, dateOfBirth, gender);
`BIGWebSearch` has no instance members, so you can make `BIGWebSearch.getBIGNumber()` a static method. Then you don't have to create a `BIGWebSearch` here.

2018-08-17 07:12 UTC, davidv1992 commented
Made requested changes

2018-09-06 13:06 UTC, merged